# Generated by Django 3.2.7 on 2021-09-20 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=80)),
                ('Location', models.CharField(max_length=120)),
                ('Owner', models.CharField(max_length=80)),
                ('Key', models.CharField(max_length=200)),
                ('Dummy', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DateTime', models.DateTimeField()),
                ('Dummy', models.CharField(max_length=1)),
                ('Facility', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.facilities')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=80)),
                ('Email', models.CharField(max_length=120)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('Company', models.CharField(max_length=120)),
                ('Password', models.CharField(max_length=200)),
                ('Dummy', models.CharField(max_length=1)),
                ('User_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.userlogs')),
            ],
        ),
        migrations.CreateModel(
            name='JoinTableUser',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Dummy', models.CharField(max_length=1)),
                ('Facility', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.facilities')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.users')),
            ],
        ),
        migrations.CreateModel(
            name='JoinTableFacility',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Dummy', models.CharField(max_length=1)),
                ('User', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.users')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.facilities')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityLog',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DateTime', models.DateTimeField()),
                ('Dummy', models.CharField(max_length=1)),
                ('User', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.users')),
            ],
        ),
        migrations.AddField(
            model_name='facilities',
            name='Faclity_log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.facilitylog'),
        ),
    ]
