# Generated by Django 3.2.7 on 2021-09-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userType',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Office user', 'Office user'), ('Field user', 'Field user')], default='Field_user', max_length=30),
        ),
    ]
