# Generated by Django 3.2.7 on 2021-10-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='userEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
