# Generated by Django 3.2.7 on 2021-09-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilities',
            name='Dummy',
        ),
        migrations.RemoveField(
            model_name='facilitylog',
            name='Dummy',
        ),
        migrations.RemoveField(
            model_name='jointablefacility',
            name='Dummy',
        ),
        migrations.RemoveField(
            model_name='jointableuser',
            name='Dummy',
        ),
        migrations.RemoveField(
            model_name='userlogs',
            name='Dummy',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Dummy',
        ),
        migrations.AddField(
            model_name='users',
            name='UserType',
            field=models.CharField(default='Field user', max_length=30),
        ),
    ]
