# Generated by Django 3.2.7 on 2021-10-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_logs_useremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='facilityLocation',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
