# Generated by Django 3.2.7 on 2021-09-21 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210920_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='Faclity_log',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.facilitylog'),
        ),
        migrations.AlterField(
            model_name='facilitylog',
            name='User',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.users'),
        ),
        migrations.AlterField(
            model_name='jointablefacility',
            name='User',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.users'),
        ),
        migrations.AlterField(
            model_name='jointablefacility',
            name='facility',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.facilities'),
        ),
        migrations.AlterField(
            model_name='jointableuser',
            name='Facility',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.facilities'),
        ),
        migrations.AlterField(
            model_name='jointableuser',
            name='User',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.users'),
        ),
        migrations.AlterField(
            model_name='userlogs',
            name='Facility',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.facilities'),
        ),
        migrations.AlterField(
            model_name='users',
            name='User_log',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.userlogs'),
        ),
    ]
