# Generated by Django 3.2.7 on 2021-09-21 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210921_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DateTime', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userlogs',
            name='Facility',
        ),
        migrations.RemoveField(
            model_name='facilities',
            name='Faclity_log',
        ),
        migrations.RemoveField(
            model_name='users',
            name='User_log',
        ),
        migrations.DeleteModel(
            name='FacilityLog',
        ),
        migrations.DeleteModel(
            name='UserLogs',
        ),
        migrations.AddField(
            model_name='logs',
            name='Facility',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.facilities'),
        ),
        migrations.AddField(
            model_name='logs',
            name='User',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.users'),
        ),
    ]
