# Generated by Django 3.2.7 on 2021-09-21 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210921_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='FacilityName',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logs',
            name='UserName',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
    ]
